/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from 'ts-interface-checker'
// tslint:disable:object-literal-key-quotes

export const AcceptMessage = t.iface([], {
  temporaryContractId: 'string',
  acceptCollateral: 'number',
  fundingPubkey: 'string',
  payoutSpk: 'string',
  payoutSerialId: 'number',
  fundingInputs: t.array('FundingInput'),
  changeSpk: 'string',
  changeSerialId: 'number',
  cetAdaptorSignatures: t.iface([], {
    ecdsaAdaptorSignatures: t.tuple(
      t.iface([], {
        signature: 'string',
      })
    ),
  }),
  refundSignature: 'string',
})

const exportedTypeSuite: t.ITypeSuite = {
  AcceptMessage,
}
export default exportedTypeSuite
