/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from 'ts-interface-checker'
// tslint:disable:object-literal-key-quotes

export const ContractInfo = t.name('SingleContractInfo')

export const SingleContractInfo = t.iface([], {
  totalCollateral: 'number',
  contractInfo: 'ContractInfoInner',
})

export const ContractInfoInner = t.iface([], {
  contractDescriptor: 'ContractDescriptor',
  oracleInfo: 'OracleInfo',
})

export const ContractDescriptor = t.union(
  'EnumeratedContractDescriptor',
  'NumericOutcomeContractDescriptor'
)

export const EnumeratedContractDescriptor = t.iface([], {
  payouts: t.array('ContractOutcome'),
})

export const NumericOutcomeContractDescriptor = t.iface([], {
  numDigits: 'number',
  payoutFunction: 'PayoutFunction',
  roundingIntervals: 'RoundingIntervals',
})

export const ContractOutcome = t.iface([], {
  outcome: 'string',
  offerPayout: 'number',
})

const exportedTypeSuite: t.ITypeSuite = {
  ContractInfo,
  SingleContractInfo,
  ContractInfoInner,
  ContractDescriptor,
  EnumeratedContractDescriptor,
  NumericOutcomeContractDescriptor,
  ContractOutcome,
}
export default exportedTypeSuite
