/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from 'ts-interface-checker'
// tslint:disable:object-literal-key-quotes

export const OracleInfo = t.name('SingleOracleInfo')

export const SingleOracleInfo = t.iface([], {
  oracleAnnouncement: 'OracleAnnouncement',
})

export const OracleAnnouncement = t.iface([], {
  announcementSignature: 'string',
  oraclePublicKey: 'string',
  oracleEvent: 'OracleEvent',
})

export const OracleEvent = t.iface([], {
  oracleNonces: t.array('string'),
  eventMaturityEpoch: 'number',
  eventDescriptor: 'EventDescriptor',
  eventId: 'string',
})

export const EventDescriptor = t.union(
  'EnumEventDescriptor',
  'DigitDecompositionEventDescriptor'
)

export const EnumEventDescriptor = t.iface([], {
  outcomes: t.array('string'),
})

export const DigitDecompositionEventDescriptor = t.iface([], {
  base: 'number',
  isSigned: 'boolean',
  unit: 'string',
  precision: 'number',
  nbDigits: 'number',
})

const exportedTypeSuite: t.ITypeSuite = {
  OracleInfo,
  SingleOracleInfo,
  OracleAnnouncement,
  OracleEvent,
  EventDescriptor,
  EnumEventDescriptor,
  DigitDecompositionEventDescriptor,
}
export default exportedTypeSuite
