/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from 'ts-interface-checker'
// tslint:disable:object-literal-key-quotes

export const PayoutPoint = t.iface([], {
  eventOutcome: 'number',
  outcomePayout: 'number',
  extraPrecision: 'number',
})

export const PayoutFunction = t.iface([], {
  payoutFunctionPieces: t.array('PayoutFunctionPiece'),
  lastEndpoint: 'PayoutPoint',
})

export const PayoutFunctionPiece = t.iface([], {
  endPoint: 'PayoutPoint',
  payoutCurvePiece: 'PayoutCurvePiece',
})

export const PayoutCurvePiece = t.name('PolynomialPayoutCurvePiece')

export const PolynomialPayoutCurvePiece = t.iface([], {
  payoutPoints: t.array('PayoutPoint'),
})

export const RoundingIntervals = t.iface([], {
  intervals: t.array('RoundingInterval'),
})

export const RoundingInterval = t.iface([], {
  beginInterval: 'number',
  roundingMod: 'number',
})

const exportedTypeSuite: t.ITypeSuite = {
  PayoutPoint,
  PayoutFunction,
  PayoutFunctionPiece,
  PayoutCurvePiece,
  PolynomialPayoutCurvePiece,
  RoundingIntervals,
  RoundingInterval,
}
export default exportedTypeSuite
